PREMIER_LEAGUE = {
    'Arsenal': [],
    'Aston Villa': [],
    'Blackburn Rovers': ['Blackburn'],
    'Bolton Wanderers': ['Bolton'],
    'Bournemouth': [],
    'Burnley': [],
    'Cardiff City': ['Cardiff'],
    'Chelsea': [],
    'Crystal Palace': [],
    'Everton': [],
    'Fulham': [],
    'Hull City': ['Hull'],
    'Leicester City': ['Leicester'],
    'Liverpool': [],
    'Manchester City': ['Man City'],
    'Manchester United': ['Man United', 'Man Utd'],
    'Newcastle United': ['Newcastle'],
    'Norwich City': ['Norwich'],
    'Queens Park Rangers': ['QPR'],
    'Reading': [],
    'Southampton': [],
    'Stoke City': ['Stoke'],
    'Sunderland': [],
    'Swansea City': ['Swansea'],
    'Tottenham Hotspur': ['Tottenham'],
    'Watford': [],
    'West Ham United': ['West Ham'],
    'West Bromwich Albion': ['West Brom', 'West Bromich Albion', 'W Brom'],
    'Wigan Athletic': ['Wigan'],
    'Wolverhampton Wanderers': ['Wolves'],
}

BUNDESLIGA = {
    'Augsburg': [],
    'Bayer Leverkusen': ['Leverkusen'],
    'Bayern Munich': [],
    'Borussia Dortmund': ['Dortmund'],
    'Borussia Monchengladbach': ['M\'gladbach', 'Borussia Moenchengladbach'],
    'Darmstadt 98': ['Darmstadt'],
    'Eintracht Braunschweig': ['Braunschweig'],
    'Eintracht Frankfurt': ['Ein Frankfurt'],
    'FC Koln': ['FC Cologne'],
    'Fortuna Dusseldorf': ['Fortuna Duesseldorf'],
    'Freiburg': [],
    'Greuther Furth': ['Greuther Fuerth'],
    'Hamburg': ['Hamburger SV'],
    'Hannover 96': ['Hannover'],
    'Hertha Berlin': ['Hertha'],
    'Hoffenheim': [],
    'Ingolstadt': [],
    'Kaiserslautern': [],
    'Mainz 05': ['Mainz'],
    'Nurnberg': ['Nuernberg'],
    'Paderborn 07': ['Paderborn'],
    'Schalke 04': [],
    'Stuttgart': ['VfB Stuttgart'],
    'Werder Bremen': [],
    'Wolfsburg': [],
}

LA_LIGA = {
    'Almeria': [],
    'Athletic Bilbao': ['Ath Bilbao'],
    'Atletico Madrid': ['Ath Madrid'],
    'Barcelona': [],
    'Celta Vigo': ['Celta'],
    'Cordoba': [],
    'Deportivo La Coruna': ['La Coruna'],
    'Eibar': [],
    'Elche': [],
    'Espanyol': ['Espanol'],
    'Getafe': [],
    'Granada': [],
    'Las Palmas': [],
    'Levante': [],
    'Malaga': [],
    'Mallorca': [],
    'Osasuna': [],
    'Racing Santander': ['Santander'],
    'Rayo Vallecano': ['Vallecano'],
    'Real Betis': ['Betis'],
    'Real Madrid': [],
    'Real Sociedad': ['Sociedad'],
    'Sevilla': [],
    'Sporting Gijon': ['Sp Gijon'],
    'Valencia': [],
    'Valladolid': [],
    'Villarreal': [],
    'Zaragoza': [],
}

LIGUE_UN = {
    'AC Ajaccio': ['Ajaccio'],
    'Angers': [],
    'Auxerre': [],
    'Bastia': ['SC Bastia'],
    'Bordeaux': [],
    'Brest': [],
    'Caen': [],
    'Dijon': [],
    'Evian': ['Evian Thonon Gaillard'],
    'Gazelec Ajaccio': ['Ajaccio GFCO', 'GFC Ajaccio'],
    'Guingamp': [],
    'Lens': [],
    'Lille': [],
    'Lorient': [],
    'Lyon': [],
    'Marseille': [],
    'Metz': [],
    'Monaco': [],
    'Montpellier': [],
    'Nancy': [],
    'Nantes': [],
    'Nice': [],
    'Paris Saint-Germain': ['Paris SG', 'Paris Saint Germain'],
    'Reims': [],
    'Rennes': [],
    'Saint-Etienne': ['St Etienne'],
    'Sochaux': [],
    'Toulouse': [],
    'Troyes': [],
    'Valenciennes': [],
}
SERIE_A = {
    'Atalanta': [],
    'Bologna': [],
    'Cagliari': [],
    'Carpi': [],
    'Catania': [],
    'Cesena': [],
    'Chievo': [],
    'Empoli': [],
    'Fiorentina': [],
    'Frosinone': [],
    'Genoa': [],
    'Hellas Verona': ['Verona'],
    'Inter': [],
    'Juventus': [],
    'Lazio': [],
    'Lecce': [],
    'Livorno': [],
    'Milan': ['AC Milan'],
    'Napoli': ['SSC Napoli'],
    'Novara': [],
    'Palermo': [],
    'Parma': [],
    'Pescara': [],
    'Roma': [],
    'Sampdoria': [],
    'Sassuolo': [],
    'Siena': ['Robur Siena'],
    'Torino': [],
    'Udinese': [],
}


def match_team_name(team):
    for league in [PREMIER_LEAGUE, BUNDESLIGA, LA_LIGA, LIGUE_UN, SERIE_A]:
        for correct_name, possible_names in league.items():
            if team == correct_name or team in possible_names:
                return correct_name

    raise Exception('No match found for team: {team}'.format(team=team))


def match_team_by_league(team, league):
    for correct_name, possible_names in league.items():
        if team == correct_name or team in possible_names:
            return correct_name

    raise Exception('No match found for team: {team}'.format(team=team))
