# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-07 15:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football_data', '0002_stadium_start_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stadium',
            options={'ordering': ['team', 'start_date']},
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ['league', 'name']},
        ),
        migrations.AddField(
            model_name='stadium',
            name='capacity',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
