# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-08 15:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('football_data', '0004_player'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('full_time_home_goals', models.PositiveSmallIntegerField()),
                ('full_time_away_goals', models.PositiveSmallIntegerField()),
                ('half_time_home_goals', models.PositiveSmallIntegerField()),
                ('half_time_away_goals', models.PositiveSmallIntegerField()),
                ('full_time_result', models.CharField(choices=[('H', 'Home win'), ('D', 'Draw'), ('A', 'Away win')], max_length=1)),
                ('half_time_result', models.CharField(choices=[('H', 'Home win'), ('D', 'Draw'), ('A', 'Away win')], max_length=1)),
            ],
        ),
        migrations.AddField(
            model_name='team',
            name='kaggle_api_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='match',
            name='away_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_matches', to='football_data.Team'),
        ),
        migrations.AddField(
            model_name='match',
            name='home_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_matches', to='football_data.Team'),
        ),
    ]
