# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-08 16:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('football_data', '0005_auto_20161008_1644'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='api_id',
            new_name='kaggle_api_id',
        ),
    ]
