# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-09 17:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('football_data', '0007_auto_20161009_1539'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='match',
            options={'verbose_name_plural': 'Matches'},
        ),
        migrations.AlterField(
            model_name='match',
            name='away_player_1',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='away_matches_p1', to='football_data.Player'),
        ),
        migrations.AlterField(
            model_name='match',
            name='away_player_10',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='away_matches_p10', to='football_data.Player'),
        ),
        migrations.AlterField(
            model_name='match',
            name='away_player_11',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='away_matches_p11', to='football_data.Player'),
        ),
        migrations.AlterField(
            model_name='match',
            name='away_player_2',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='away_matches_p2', to='football_data.Player'),
        ),
        migrations.AlterField(
            model_name='match',
            name='away_player_3',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='away_matches_p3', to='football_data.Player'),
        ),
        migrations.AlterField(
            model_name='match',
            name='away_player_4',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='away_matches_p4', to='football_data.Player'),
        ),
        migrations.AlterField(
            model_name='match',
            name='away_player_5',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='away_matches_p5', to='football_data.Player'),
        ),
        migrations.AlterField(
            model_name='match',
            name='away_player_6',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='away_matches_p6', to='football_data.Player'),
        ),
        migrations.AlterField(
            model_name='match',
            name='away_player_7',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='away_matches_p7', to='football_data.Player'),
        ),
        migrations.AlterField(
            model_name='match',
            name='away_player_8',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='away_matches_p8', to='football_data.Player'),
        ),
        migrations.AlterField(
            model_name='match',
            name='away_player_9',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='away_matches_p9', to='football_data.Player'),
        ),
        migrations.AlterField(
            model_name='match',
            name='home_player_1',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='home_matches_p1', to='football_data.Player'),
        ),
        migrations.AlterField(
            model_name='match',
            name='home_player_10',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='home_matches_p10', to='football_data.Player'),
        ),
        migrations.AlterField(
            model_name='match',
            name='home_player_11',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='home_matches_p11', to='football_data.Player'),
        ),
        migrations.AlterField(
            model_name='match',
            name='home_player_2',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='home_matches_p2', to='football_data.Player'),
        ),
        migrations.AlterField(
            model_name='match',
            name='home_player_3',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='home_matches_p3', to='football_data.Player'),
        ),
        migrations.AlterField(
            model_name='match',
            name='home_player_4',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='home_matches_p4', to='football_data.Player'),
        ),
        migrations.AlterField(
            model_name='match',
            name='home_player_5',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='home_matches_p5', to='football_data.Player'),
        ),
        migrations.AlterField(
            model_name='match',
            name='home_player_6',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='home_matches_p6', to='football_data.Player'),
        ),
        migrations.AlterField(
            model_name='match',
            name='home_player_7',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='home_matches_p7', to='football_data.Player'),
        ),
        migrations.AlterField(
            model_name='match',
            name='home_player_8',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='home_matches_p8', to='football_data.Player'),
        ),
        migrations.AlterField(
            model_name='match',
            name='home_player_9',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='home_matches_p9', to='football_data.Player'),
        ),
    ]
