# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-10 18:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football_data', '0011_auto_20161010_0030'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='has_played_match',
            field=models.BooleanField(default=False),
        ),
    ]
