# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-25 13:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('football_data', '0015_decisiontreemodel_predictivemodel'),
        ('football_data', '0013_auto_20170121_1229'),
    ]

    operations = [
    ]
