# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-27 22:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football_data', '0020_auto_20170227_2002'),
    ]

    operations = [
        migrations.AddField(
            model_name='datafeature',
            name='column_index',
            field=models.IntegerField(default=0, help_text='The column index for this feature in the training data (1-indexed)'),
            preserve_default=False,
        ),
    ]
