# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-27 23:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('football_data', '0021_datafeature_column_index'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='datafeature',
            unique_together=set([('model', 'column_index')]),
        ),
    ]
