# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-28 13:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football_data', '0025_trainingdrill'),
    ]

    operations = [
        migrations.AddField(
            model_name='datafeature',
            name='positive_weight',
            field=models.NullBooleanField(editable=False),
        ),
        migrations.AddField(
            model_name='datafeature',
            name='std_dev',
            field=models.FloatField(default=0, editable=False),
        ),
    ]
