# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-28 13:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football_data', '0026_auto_20170228_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datafeature',
            name='positive_weight',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='datafeature',
            name='std_dev',
            field=models.FloatField(default=0),
        ),
    ]
