# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-28 13:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football_data', '0027_auto_20170228_1311'),
    ]

    operations = [
        migrations.AddField(
            model_name='machinelearningmodel',
            name='target_feature_name',
            field=models.CharField(default='feature', help_text='The name of the target feature column as it appears in the training data', max_length=60),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='datafeature',
            name='data_type',
            field=models.CharField(choices=[('bool', 'Boolean'), ('float64', 'Float'), ('int64', 'Integer')], max_length=10),
        ),
        migrations.AlterField(
            model_name='datafeature',
            name='display_name',
            field=models.CharField(blank=True, help_text='The readable name of this feature', max_length=40, null=True),
        ),
    ]
