# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-07 10:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football_data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stadium',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
