# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-10 16:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football_data', '0002_auto_20170310_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='training_data',
            field=models.BooleanField(default=True),
        ),
    ]
