# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-13 10:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('football_data', '0003_appmatch'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appmatch',
            old_name='away_fouls_committed',
            new_name='away_fouls',
        ),
        migrations.RenameField(
            model_name='appmatch',
            old_name='home_fouls_committed',
            new_name='home_fouls',
        ),
    ]
