# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-10 16:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('football_data', '0005_auto_20170310_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='coach',
            name='predictive_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='football_data.MachineLearningModel'),
        ),
        migrations.AddField(
            model_name='machinelearningmodel',
            name='default',
            field=models.BooleanField(default=False, help_text='Is this the default model? (There can only be one)'),
        ),
    ]
