# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-02 10:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football_data', '0005_appmatch_coach_team_is_home_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='datafeature',
            name='max_alteration',
            field=models.FloatField(default=0, help_text='The maximum achievable alteration for this feature'),
        ),
        migrations.AddField(
            model_name='datafeature',
            name='min_alteration',
            field=models.FloatField(default=0, help_text='The minimum achievable alteration for this feature'),
        ),
    ]
