# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-11 17:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('football_data', '0006_auto_20170310_1632'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppMatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('at_home', models.BooleanField()),
                ('winning_at_half_time', models.BooleanField()),
                ('half_time_goals', models.PositiveSmallIntegerField()),
                ('opp_half_time_goals', models.PositiveSmallIntegerField()),
                ('possession', models.DecimalField(decimal_places=1, max_digits=3)),
                ('opp_possession', models.DecimalField(decimal_places=1, max_digits=3)),
                ('total_shots', models.PositiveSmallIntegerField()),
                ('opp_total_shots', models.PositiveSmallIntegerField()),
                ('shots_on_target', models.PositiveSmallIntegerField()),
                ('opp_shots_on_target', models.PositiveSmallIntegerField()),
                ('corners', models.PositiveSmallIntegerField()),
                ('opp_corners', models.PositiveSmallIntegerField()),
                ('fouls', models.PositiveSmallIntegerField()),
                ('opp_fouls', models.PositiveSmallIntegerField()),
                ('yellow_cards', models.PositiveSmallIntegerField()),
                ('opp_yellow_cards', models.PositiveSmallIntegerField()),
                ('red_cards', models.PositiveSmallIntegerField()),
                ('opp_red_cards', models.PositiveSmallIntegerField()),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='football_data.Coach')),
            ],
        ),
    ]
