# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-11 17:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football_data', '0007_appmatch'),
    ]

    operations = [
        migrations.AddField(
            model_name='appmatch',
            name='won_match',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
