# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-04 14:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football_data', '0008_trainingdrill_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='datafeature',
            name='message',
            field=models.TextField(blank=None, help_text='Why does improving this stat help a team?', null=True),
        ),
    ]
