# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-09 23:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football_data', '0010_auto_20161010_0019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='away_offsides',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='home_offsides',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
