# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-11 12:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('football_data', '0013_auto_20161111_1230'),
    ]

    operations = [
        migrations.RenameField(
            model_name='match',
            old_name='home_draw_average_odds',
            new_name='draw_average_odds',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='home_draw_max_odds',
            new_name='draw_max_odds',
        ),
    ]
