# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-27 19:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football_data', '0018_datafeature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machinelearningmodel',
            name='algorithm',
            field=models.CharField(choices=[('LogisticRegression', 'LogisticRegression'), ('GradientBoosting', 'GradientBoosting')], max_length=50),
        ),
        migrations.AlterField(
            model_name='machinelearningmodel',
            name='training_data',
            field=models.FileField(upload_to='training_data'),
        ),
    ]
