# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-27 23:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('football_data', '0022_auto_20170227_2307'),
    ]

    operations = [
        migrations.CreateModel(
            name='BooleanDataFeature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(help_text='The readable name of this feature', max_length=40)),
                ('name', models.CharField(help_text='The name as it appears in the dataset', max_length=50)),
                ('column_index', models.IntegerField(help_text='The column index for this feature in the training data (1-indexed)')),
                ('is_target_feature', models.BooleanField(default=False)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boolean_features', to='football_data.MachineLearningModel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FloatDataFeature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(help_text='The readable name of this feature', max_length=40)),
                ('name', models.CharField(help_text='The name as it appears in the dataset', max_length=50)),
                ('column_index', models.IntegerField(help_text='The column index for this feature in the training data (1-indexed)')),
                ('is_target_feature', models.BooleanField(default=False)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='float_features', to='football_data.MachineLearningModel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IntegerDataFeature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(help_text='The readable name of this feature', max_length=40)),
                ('name', models.CharField(help_text='The name as it appears in the dataset', max_length=50)),
                ('column_index', models.IntegerField(help_text='The column index for this feature in the training data (1-indexed)')),
                ('is_target_feature', models.BooleanField(default=False)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integer_features', to='football_data.MachineLearningModel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterUniqueTogether(
            name='datafeature',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='datafeature',
            name='model',
        ),
        migrations.DeleteModel(
            name='DataFeature',
        ),
    ]
