# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-28 00:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('football_data', '0023_auto_20170227_2316'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataFeature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(help_text='The readable name of this feature', max_length=40)),
                ('name', models.CharField(help_text='The name as it appears in the dataset', max_length=50)),
                ('column_index', models.IntegerField(help_text='The column index for this feature in the training data (1-indexed)')),
                ('is_target_feature', models.BooleanField(default=False)),
                ('data_type', models.CharField(choices=[('bool', 'Boolean'), ('float', 'Float'), ('int', 'Integer')], max_length=10)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='football_data.MachineLearningModel')),
            ],
        ),
        migrations.RemoveField(
            model_name='booleandatafeature',
            name='model',
        ),
        migrations.RemoveField(
            model_name='floatdatafeature',
            name='model',
        ),
        migrations.RemoveField(
            model_name='integerdatafeature',
            name='model',
        ),
        migrations.DeleteModel(
            name='BooleanDataFeature',
        ),
        migrations.DeleteModel(
            name='FloatDataFeature',
        ),
        migrations.DeleteModel(
            name='IntegerDataFeature',
        ),
        migrations.AlterUniqueTogether(
            name='datafeature',
            unique_together=set([('model', 'column_index')]),
        ),
    ]
