# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-01 14:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football_data', '0029_datafeature_mean'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machinelearningmodel',
            name='algorithm',
            field=models.CharField(choices=[('LogisticRegression', 'LogisticRegression'), ('SVM', 'SVM')], max_length=50),
        ),
    ]
