# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-01 17:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='NonTeamMatchStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('wind_speed', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('attendance', models.PositiveSmallIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('venue', models.CharField(blank=True, max_length=100, null=True)),
                ('lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TeamMatchStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_time_goals_count', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('half_time_goals_count', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('full_time_goals_against_count', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('half_time_goals_against_count', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('possession', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('total_shots', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('total_shots_allowed', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('shots_on_target', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('shots_on_target_allowed', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('corners_for', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('corners_against', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('offsides_committed', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('offsides_received', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('tackles', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('interceptions', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('interceptions_againts', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('fouls_committed', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('fouls_against', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('yellow_cards', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('red_cards', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('match', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='football_data.Match')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_stats', to='football_data.Team')),
            ],
        ),
        migrations.AddField(
            model_name='match',
            name='away_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_matches', to='football_data.Team'),
        ),
        migrations.AddField(
            model_name='match',
            name='home_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_matches', to='football_data.Team'),
        ),
    ]
